import { useState } from 'react';
import HighwayPreview from './components/HighwayPreview';
import './Landing.css';

const packURL = '/downloads/vibe-hero-indie-starter.json';
const extensionURL = '/downloads/vibe-hero-extension.zip';
const artists = ['Feist', 'Yeah Yeah Yeahs', 'Radiohead', 'The Shins', 'Interpol', 'MGMT', 'The Killers', 'Arctic Monkeys'];
export default function Landing() {
  const [showSongs, setShowSongs] = useState(false), [songs, setSongs] = useState([]), [error, setError] = useState('');
  async function browsePack() {
    if (showSongs) { setShowSongs(false); return; }
    try {
      if (!songs.length) { const response = await fetch(packURL); if (!response.ok) throw Error(); const pack = await response.json(); setSongs(pack.charts); }
      setShowSongs(true); setError('');
    } catch { setError('The track list could not load. Try the pack download instead.'); }
  }
  return <div className="launch">
    <nav className="launch-nav" aria-label="Main navigation"><a className="launch-brand" href="/" aria-label="Vibe Hero home">vibehero<span>★</span></a><div><a href="#setlist">The setlist</a><a href="#how">How to play</a><a className="launch-nav-cta" href="/play">Play the beta ↗</a></div></nav>
    <main>
      <section className="launch-hero">
        <div className="launch-hero-copy"><p className="launch-kicker"><span /> INDEPENDENT RHYTHM GAME · PUBLIC BETA</p><h1>Your music.<br/>Your <em>main stage.</em></h1><p className="launch-lede">Turn the songs you love into a five-fret fever dream. Catch the riff. Hold the note. Make the crowd lose it.</p><div className="launch-actions"><a className="launch-button" href="/play">Play the browser beta <span>↗</span></a><a className="launch-text-link" href="#download">Get the YouTube extension ↓</a></div><p className="launch-fine">Keyboard ready. Headphones highly encouraged.</p><div className="launch-keys" aria-label="Default fret keys"><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd><kbd>F</kbd><kbd>G</kbd><span>FIVE KEYS.<br/>ALL FEELING.</span></div></div>
        <div className="launch-stage"><div className="launch-orbit"/><span className="launch-stage-label">LIVE FROM YOUR BEDROOM</span><HighwayPreview animated/><div className="launch-stage-ticket"><span>ADMIT ONE</span><strong>YOU’RE UP.</strong><span>NO GUITAR REQUIRED</span></div><p className="launch-stage-caption">HIT THE LINE. KEEP THE STREAK.</p></div>
      </section>
      <div className="launch-marquee" aria-hidden="true"><span>MAKE SOME NOISE</span> ✳ <span>CHASE THE PERFECT SET</span> ✳ <span>ONE MORE SONG</span> ✳</div>
      <section className="launch-setlist launch-section" id="setlist"><div className="launch-section-title"><p className="launch-kicker">01 / THE OPENING SET</p><h2>All killer.<br/><em>Less setup.</em></h2><p>49 prepared charts from the 2000s indie playlist. Download once, import the whole set, and pick your next song.</p><a className="launch-button" href={packURL} download>Download the starter pack ↓</a><p className="launch-fine">Free beta pack · Chart data only. Music plays on YouTube.</p></div><div className="launch-setlist-card"><div className="launch-setlist-top"><span>VOLUME 001</span><span>49 TRACKS</span></div><h3>The indie<br/>afterparty.</h3><p className="launch-artist-list">{artists.map(artist=><span key={artist}>{artist}</span>)}</p><div className="launch-setlist-bottom"><span>+ 41 MORE RECORDINGS</span><button onClick={browsePack} aria-expanded={showSongs}>{showSongs ? 'Hide' : 'See'} full setlist {showSongs ? '−' : '+'}</button></div>{error && <p role="status">{error}</p>}{showSongs && <ol className="launch-song-list">{songs.map(song=><li key={song.youtubeId}><a href={`https://www.youtube.com/watch?v=${song.youtubeId}`} target="_blank" rel="noreferrer">{song.title} ↗</a></li>)}</ol>}</div></section>
      <section className="launch-section launch-how" id="how"><div className="launch-section-title"><p className="launch-kicker">02 / SOUNDCHECK</p><h2>From library<br/>to <em>live wire.</em></h2></div><div className="launch-steps"><article><span>01</span><div><h3>Pick your stage.</h3><p>Play a local audio file in the browser. For music-video backdrops, install the extension and open a song on YouTube.</p></div></article><article><span>02</span><div><h3>Bring the whole set.</h3><p>Open the extension’s My song library and choose Import a prepared setlist. One JSON pack adds every included song to your own library—no repeat listening.</p></div></article><article><span>03</span><div><h3>Find your groove.</h3><p>Start with four-key Easy, work up to Expert, or switch chords off. Sustain the long notes and press Space when your star power is charged.</p></div></article></div></section>
      <section className="launch-features"><article><span>♫</span><h3>Notes that listen.</h3><p>Audio-driven attacks, automatic tempo estimates, and room to breathe when the track goes quiet. Full-mix analysis, still getting better.</p></article><article><span>✳</span><h3>Give it everything.</h3><p>Hit flames, sustained notes, streaks, and 16 seconds of star power. Keep the crowd with you—or restart the set.</p></article><article><span>↗</span><h3>Make it personal.</h3><p>Save your name and scores. Build a library of prepared songs. Your beta library and history stay in your browser.</p></article></section>
      <section className="launch-section launch-download" id="download"><div><p className="launch-kicker">03 / BACKSTAGE PASS</p><h2>One more song.<br/><em>Then another.</em></h2><p>The beta is open. Play in your browser today, or bring the fretboard right onto YouTube with the desktop Chrome extension.</p><div className="launch-actions"><a className="launch-button" href={extensionURL} download>Download extension ↓</a><a href="/play-on-youtube.html">Installation guide ↗</a></div><p className="launch-fine">Chrome, Edge, or Brave on desktop · Manual installation for this beta</p></div><aside className="launch-pass"><div className="launch-pass-top">THE PLANNED FULL RELEASE <span>001</span></div><h3>Your backstage pass.</h3><strong className="launch-price">$9.99<span>ONE TIME</span></strong><p>Our planned launch price. The beta is free while we finish the release.</p><div className="launch-checkout-status">Checkout coming soon</div><p className="launch-fine">Purchases are not open yet. A standalone Mac app is in planning; this download is the browser extension.</p></aside></section>
      <section className="launch-faq launch-section"><h2>A few things<br/>before the encore.</h2><div><details><summary>Can I bring my own songs?</summary><p>Yes. Open the browser game to analyze a local audio file. In the extension, prepare a YouTube song quietly or import a prepared song pack into My song library. Playlist URLs are not yet a self-service bulk preparation feature on this website.</p></details><details><summary>Does the starter pack include music?</summary><p>No. It contains timing and note data for 49 exact YouTube recordings. YouTube supplies playback, so video availability and ads can vary. The playlist’s unavailable Little Lion Man upload is excluded.</p></details><details><summary>Is this a Mac app?</summary><p>The current release runs in a desktop browser, with a separate YouTube extension. A direct-download Mac app is planned, but is not available to purchase or download yet.</p></details><details><summary>Can I use a guitar controller?</summary><p>The web game includes gamepad mapping. The YouTube extension accepts keyboard input, including controllers mapped to keys. Wireless Wii guitar support on newer Macs remains experimental.</p></details><details><summary>Where do my songs and scores go?</summary><p>They stay in the browser where you saved them. Export backups before removing the extension or clearing browser data. Global leaderboards and account sync are not live yet.</p></details></div></section>
    </main><footer className="launch-footer"><a className="launch-brand" href="/">vibehero<span>★</span></a><span>BUILT FOR THE “ONE MORE SONG” PEOPLE.</span><a href="/play">Take the stage ↗</a><p>Independent project. Not affiliated with Guitar Hero, Activision, or YouTube.</p></footer>
  </div>;
}
